### ISSUE TITLE
Why to  hardcode password?

### ISSUE THREAD

**Issue by gau1991** [joshisumit/easy_wordpress#2]
> This script installs mysql with username=root and password=sumit. You can change your mysql password after installation.

Its a security risk to hardcode passwords, you must generate random password runtime

**Comment by gau1991** [comment]
Same for WordPress database passwords

```
/** MySQL database username */
define('DB_USER', 'wordpuser');

/** MySQL database password */
define('DB_PASSWORD', 'password');
```

**Comment by joshisumit** [comment]
## Wordpress Database Configuration

Previously `wordpuser` has access on all DBs. So generated custom MYSQL user for each site.
Also added code for generating password at runtime.

```
    usrname=$(echo $dom | cut -d"." -f1)

    wp_user+=$usrname
    wp_user+="user"
    #echo "New MySQL database username $wp_user"

    #Generates random password of 10 characters for wordpress DB user 
    wp_passwd=$(date +"%s" | md5sum | cut -c -10)
```

If provided domain name is example.com, then `wp-config.php` is:

```
 /** MySQL database username */
 define('DB_USER', 'exampleuser');

 /** MySQL database password */
 define('DB_PASSWORD', '471d2a817a');
```

**Comment by joshisumit** [comment]
## MySQL Configuration

Added code which generates random password. It also prompts the generated password,so that user can use in `mysql_secure_installation`.

```
function install_mysql
{
    #echo "This function will install mysql"
    #sudo apt-get update || ( echo "Update Failed" && exit )

    #added Generate random password for mysql root user
    #It will prompt the generated password....
    msql_passwd=$(date +"%s" | md5sum | cut -c -10)
    echo "MySQL password is $msql_passwd"

    #Set MySQL password in advance
    echo "mysql-server mysql-server/root_password password $msql_passwd" | sudo debconf-set-selections
    echo "mysql-server mysql-server/root_password_again password $msql_passwd" | sudo debconf-set-selections

    #Install MySQL
    sudo apt-get -y install mysql-server php5-mysql || ( echo "MySQL installation Failed" && exit )

    #configure MySQL
    sudo mysql_install_db

    #user should change his root password during this phase
    sudo /usr/bin/mysql_secure_installation

    return 0
}
```

**Comment by joshisumit** [comment]
For MySQL installation we can adopt any of the two:
1. At installation time ask user to set his password (which is more secure. User interaction is required.)
2. Completely automate the MySQL installation procedure. Genrate password at runtime.
   For that we require automation of `mysql_secure_installation`.
