### ISSUE TITLE
nginx 502 - bad gateway

### ISSUE THREAD

**Issue by gau1991** [joshisumit/easy_wordpress#5]
Users getting 502 when they open site into browser. As you are using `fastcgi_pass 127.0.0.1:9000;` in Nginx config, 

Instead keeping instruction on Readme you can also do that inside your script, so that no one will face 502 bad gateway

**Comment by joshisumit** [comment]
Added following line in `install_php5-fpm` function:

`sudo sed -i "/listen = / s/\/var\/run\/php5-fpm\.sock/127\.0\.0\.1\:9000/" /etc/php5/fpm/pool.d/www.conf`
